In [1]:
import pandas as pd
import pymongo

movies_df = pd.read_csv('movies.csv')
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [2]:
ratings_df = pd.read_csv('ratings.csv')
ratings_df.head()

   userId  movieId  rating
0  122270     8360     3.5
1   49018       32     2.0
2   89527   109374     3.5
3  106704     1060     3.0
4   47791     1732     2.0

In [7]:
links_df = pd.read_csv('links.csv')
links_df.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [8]:
# df should be converted into dict before we push it to mongodb

movies = movies_df.to_dict(orient='records')
ratings = ratings_df.to_dict(orient='records')
links = links_df.to_dict(orient='records')

# data

In [5]:
DB_NAME = "Movie"
# COLLECTION_NAME = "Movie-Data"
CONNECTION_URL = "mongodb+srv://saikrishnabothkurwar6_db_user:8UgFBEFWL6wfsIHG@cluster0.o39bjxe.mongodb.net/?appName=Cluster0"

# above, either remove your credentials or delete the mongoDB resource bofore pushing it to github.

In [9]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
# collection = data_base[COLLECTION_NAME]

In [10]:
# Create collections
movies_collection = data_base["movies"]
ratings_collection = data_base["ratings"]
links_collection = data_base["links"]

In [11]:
# Uploading data to MongoDB
rec_movies = movies_collection.insert_many(movies)
rec_ratings = ratings_collection.insert_many(ratings)
rec_links = links_collection.insert_many(links)

In [12]:
# Load back data from mongodb

df = pd.DataFrame(list(ratings_collection.find()))
df.head(2)

                        _id  userId  movieId  rating
0  69e20ad317855f5e26f0741f  122270     8360     3.5
1  69e20ad317855f5e26f07420   49018       32     2.0

In [ ]:
## If you are getting timeout issue

# import certifi
# client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# # TO CREATE THE DATABASE
# data_base = client[DB_NAME]
# collection = data_base[COLLECTION_NAME]
# # TO INSERT DATA INTO THE COLLECTION
# rec = collection.insert_many(data)